### go through ingress / gateway

### for podinfo
GET http://localhost:8080/
Host: podinfo.local

### for dashboard
GET https://localhost:8443/
Host: dashboard.local

### by subpath
GET https://localhost:8443/dashboard/

