### go through ingress / gateway

### for podinfo
GET http://localhost:8080/
Host: podinfo.local

### for dashboard
### REST version:
GET https://localhost:8443/
Host: dashboard.local

### Browser version - hosts file modified
GET https://dashboard.local:8443/

