apiVersion: v1
kind: Namespace
metadata:
  name: podinfo2
  labels:
    name: podinfo2
---
apiVersion: v1
kind: Namespace
metadata:
  name: dashboard
  labels:
    name: dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane
  labels:
    name: crossplane
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
---
### namespace for cross namespace gateway objects
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    name: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-gateway
  labels:
    name: nginx-gateway
