# # # repo
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kongrepo
  namespace: kong-system
spec:
  interval: 1h
  url: https://charts.konghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong-operator
  namespace: kong-system
spec:
  chart:
    spec:
      chart: kong-operator
      version: 1.0.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kongrepo
  interval: 1h
  values: {}

