---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-podinfo
  namespace: podinfo2
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: 6.9.4
  interval: 1h
  values:
    replicaCount: 3
    resources:
      requests:
        cpu: 3m

